### ISSUE TITLE
Request: Add fade when changing quotes

### ISSUE THREAD

**Issue by simgust** [cdmoro/literature-clock#8]
I would love for the quotes to change with a fade instead of being instant. Having it on a secondary monitor within view makes the changes a bit distracting.

**Comment by cdmoro** [comment]
Hey, this is an interest feature, how do you think the transition should be? the old quote should fade out and the new one fade in, or just one of them? thanks

**Comment by simgust** [comment]
Yes, I think the old one should fade out and the new one fade in (at least in the zen mode)! :)

Some additional feedback: I think the timeline bar should fade out instead of animate backwards, which feels strange. I would also love some more font options (the current ones are very wacky). I can recommend [TT2020](https://github.com/ctrlcctrlv/TT2020), which is a very realistic typewriter font. I would also love to have more classic serif typefaces, in addition to the default system sans-serif fonts (on macOS at least that would look very good). Maybe even an option to choose from your own system's fonts?

Thank you for making this thing and taking the time to read this feedback :)

**Comment by cdmoro** [comment]
Hey, I made a PR with this change, check it out and tell me what you think! https://deploy-preview-9--literatureclock.netlify.app/?fade=true

Regarding the other things you mentioned:

### Timeline animation

This is a bit tricky because the issue with backwards animation is caused by how the browsers handle CSS animations, to save resources, when a tab is inactive, the animations are paused, so when the tab is active again, the animation starts from the same point it was before. To solve this issue I replaced the CSS animation with a JS-based animation (I included it in the same PR so you should be able to see it in action!)

### Fonts

At the moment, I wouldn't like to replace the way fonts are handled. I relied on Google Fonts for that because it was the easiest approach. BUT, there is a way to use any font from Google Fonts using the `fonts` query param.

I found this serif font in Google Fonts, called [Abril Fatface](https://fonts.google.com/specimen/Abril+Fatface), I can copy the name as it is in the URL (`Abril+Fatface`) and paste it on the clock https://literatureclock.netlify.app/?font=Abril+Fatface you should see the clock with this font.

Let's try another font, [Edu Australia VIC WA NT Hand Guides](https://fonts.google.com/specimen/Edu+AU+VIC+WA+NT+Guides), https://literatureclock.netlify.app/?font=Edu+AU+VIC+WA+NT+Guides, and voila!

Let me know what you think! I will merge the PR in a few days as I like the fade effect :D
